import { v4 as uuidv4 } from 'uuid'
import { generateLonLatFloat, log, overwriteLonLatObj } from './index'
import merge from 'lodash.merge'
const RIDES_DATA_STATIC = {
  took: 2,
  timed_out: false,
  _shards: { total: 1, successful: 1, skipped: 0, failed: 0 },
  hits: {
    total: { value: 28, relation: 'eq' },
    max_score: null,
    hits: [
      {
        _index: 'rides',
        _type: '_doc',
        _id: 0,
        _score: null,
        _source: {
          id: 0,
          title: 'Meuble tv',
          description: null,
          owner_id: 1511,
          from_lat: 48.85658,
          to_lat: 45.75889,
          ga_sent: null,
          price: 5400,
          created_at: '2022-03-18T14:28:46.320+01:00',
          updated_at: '2022-03-18T14:28:58.343+01:00',
          from_lng: 2.35183,
          to_lng: 4.84139,
          from_is_flexible: false,
          from_pickup_date: '2022-03-21T12:00:00.000+01:00',
          to_is_flexible: false,
          to_pickup_date: '2022-03-31T23:59:59.999+02:00',
          is_packaged: null,
          is_passenger: false,
          volume: 0.3,
          environment: 'objects',
          deleted_at: null,
          slug: 'meuble-tv-2a14b24e-c862-417e-9e2d-4bad063c75f6',
          rider_extra_information: '',
          from_need_help: false,
          from_need_help_floor: null,
          from_need_help_elevator: null,
          from_need_help_furniture_lift: false,
          to_need_help: false,
          to_need_help_floor: null,
          to_need_help_elevator: null,
          to_need_help_furniture_lift: false,
          state: 'published',
          moderated_by: null,
          moderated_at: null,
          moderated_reason_content: null,
          owner_status: 'sender',
          completed_at: null,
          published_at: '2022-03-18T14:28:46.375+01:00',
          gat_sent: false,
          last_activity_at: '2022-03-18T14:28:46.323+01:00',
          validated_by_id: null,
          fees: 1200,
          v2_id: null,
          environment_kind: null,
          api_application_id: null,
          seller_tracking: 'E2CDD16E1974D8C0',
          buyer_tracking: '132152975D6856A8',
          external_id: null,
          content_value: null,
          offers_count: 0,
          last_edited_at: '2022-03-18T14:28:58.343+01:00',
          last_standby_at: null,
          managed_by_id: null,
          is_automatic: false,
          sinister: false,
          removed_at: null,
          price_formula: null,
          has_heavy_objects: false,
          packaging_needed: false,
          suggested_price: 6600,
          published_price: null,
          rider_price: 5400,
          owner: {
            id: 1511,
            last_sign_in_at: '2022-01-17T15:47:11.873+01:00',
            nickname: 'Emma Z.',
            gender: 'F',
            firstname: 'Emma',
            business_name: '',
            phone_verified: true,
            role: 'customer',
            sign_up_finished: true,
            v2_id: null,
            deleted_at: null,
            rate: null,
            banned_at: null,
            referral_code: 'EMMEZ171',
            accepted_cgu_version: 2,
            rating_count: 0,
            email_verified: true,
            response_percent: 0,
            kyc_validated: false,
            identity_validated: false,
            role_label: 'Particulier',
            current_cgu_version: 2,
          },
          ride_state_histories: [],
          previous_pay_in: false,
          conversations: { count: 0, unreaded_messages: 0 },
          from_address: 'Paris, 75004',
          to_address: 'Lyon, 69003',
          from_country: 'France',
          to_country: 'France',
          offers_made_by_others_count: 0,
          volume_only_for_pro: false,
          photos: [],
          from: { lat: 48.85658, lon: 2.35183 },
          to: { lat: 45.75889, lon: 4.84139 },
          distance: 392.21852717235214,
          bearing: 150.48998216586,
        },
        sort: [1647610138343],
      },
      {
        _index: 'rides',
        _type: '_doc',
        _id: 1,
        _score: null,
        _source: {
          id: 1,
          title: 'Test',
          description: null,
          owner_id: 218,
          from_lat: 50.63194,
          to_lat: 36.7,
          ga_sent: null,
          price: 4100,
          created_at: '2022-03-15T18:08:54.970+01:00',
          updated_at: '2022-03-15T18:09:11.471+01:00',
          from_lng: 3.0575,
          to_lng: -6.11667,
          from_is_flexible: false,
          from_pickup_date: '2022-03-17T12:00:00.000+01:00',
          to_is_flexible: false,
          to_pickup_date: '2022-03-24T23:59:59.999+01:00',
          is_packaged: null,
          is_passenger: false,
          volume: 0.6,
          environment: 'objects',
          deleted_at: null,
          slug: 'test-a40d8dd8-b9aa-4dc7-a3aa-ffe3be3b2fd4',
          rider_extra_information: '',
          from_need_help: false,
          from_need_help_floor: null,
          from_need_help_elevator: null,
          from_need_help_furniture_lift: false,
          to_need_help: false,
          to_need_help_floor: null,
          to_need_help_elevator: null,
          to_need_help_furniture_lift: false,
          state: 'published',
          moderated_by: null,
          moderated_at: null,
          moderated_reason_content: null,
          owner_status: 'recipient',
          completed_at: null,
          published_at: '2022-03-15T18:08:55.059+01:00',
          gat_sent: false,
          last_activity_at: '2022-03-15T18:08:54.974+01:00',
          validated_by_id: null,
          fees: 900,
          v2_id: null,
          environment_kind: null,
          api_application_id: null,
          seller_tracking: 'A06B971B2C6E2983',
          buyer_tracking: '8F4D5FB43952894D',
          external_id: null,
          content_value: null,
          offers_count: 0,
          last_edited_at: '2022-03-15T18:09:11.471+01:00',
          last_standby_at: null,
          managed_by_id: null,
          is_automatic: false,
          sinister: false,
          removed_at: null,
          price_formula: null,
          has_heavy_objects: false,
          packaging_needed: false,
          suggested_price: 9900,
          published_price: null,
          rider_price: 4100,
          owner: {
            id: 218,
            last_sign_in_at: '2022-03-11T20:09:02.108+01:00',
            nickname: 'Transporteur P.',
            gender: 'F',
            firstname: 'Transporteur',
            business_name: '',
            phone_verified: true,
            role: 'customer',
            sign_up_finished: true,
            v2_id: null,
            deleted_at: null,
            rate: 0,
            banned_at: null,
            referral_code: 'JULTP1510',
            accepted_cgu_version: 2,
            rating_count: 3,
            email_verified: true,
            response_percent: 100,
            avatar:
              '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2NFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd018116750a8e8b98d7313db2a3d97275616a69/maxresdefault%20(1).jpg?disposition=attachment',
            avatar_key: 'gf20d2kphgkc9zmto4g8u9fbcv9d',
            kyc_validated: true,
            identity_validated: false,
            role_label: 'Particulier',
            current_cgu_version: 2,
          },
          ride_state_histories: [],
          previous_pay_in: false,
          conversations: { count: 0, unreaded_messages: 0 },
          from_address: 'Lille, 59800',
          to_address: 'Jerez de la Frontera, 11405',
          from_country: 'France',
          to_country: 'Spain',
          offers_made_by_others_count: 0,
          volume_only_for_pro: false,
          photos: [],
          from: { lat: 50.63194, lon: 3.0575 },
          to: { lat: 36.7, lon: -6.11667 },
          distance: 1712.844302555822,
          bearing: 208.76730023577312,
        },
        sort: [1647364151471],
      },
      {
        _index: 'rides',
        _type: '_doc',
        _id: 2,
        _score: null,
        _source: {
          id: 2,
          title: 'Guitarre',
          description: null,
          owner_id: 218,
          from_lat: 50.63194,
          to_lat: 50.35917,
          ga_sent: null,
          price: 2900,
          created_at: '2022-03-11T10:02:09.005+01:00',
          updated_at: '2022-03-15T10:36:20.276+01:00',
          from_lng: 3.0575,
          to_lng: 3.525,
          from_is_flexible: true,
          from_pickup_date: '2022-03-15T12:00:00.000+01:00',
          to_is_flexible: false,
          to_pickup_date: '2022-06-30T23:59:59.999+02:00',
          is_packaged: null,
          is_passenger: false,
          volume: 0.6,
          environment: 'objects',
          deleted_at: null,
          slug: 'guitarre',
          rider_extra_information: '',
          from_need_help: false,
          from_need_help_floor: null,
          from_need_help_elevator: null,
          from_need_help_furniture_lift: false,
          to_need_help: false,
          to_need_help_floor: null,
          to_need_help_elevator: null,
          to_need_help_furniture_lift: false,
          state: 'published',
          moderated_by: null,
          moderated_at: null,
          moderated_reason_content: null,
          owner_status: 'sender',
          completed_at: null,
          published_at: '2022-03-15T10:36:20.271+01:00',
          gat_sent: false,
          last_activity_at: '2022-03-11T10:02:09.010+01:00',
          validated_by_id: null,
          fees: 600,
          v2_id: null,
          environment_kind: null,
          api_application_id: null,
          seller_tracking: 'C14DD027E015373D',
          buyer_tracking: '87E2E4E145F40A12',
          external_id: null,
          content_value: null,
          offers_count: 0,
          last_edited_at: '2022-03-15T10:36:20.256+01:00',
          last_standby_at: null,
          managed_by_id: null,
          is_automatic: false,
          sinister: false,
          removed_at: null,
          price_formula: null,
          has_heavy_objects: false,
          packaging_needed: false,
          suggested_price: 3500,
          published_price: null,
          rider_price: 2900,
          owner: {
            id: 218,
            last_sign_in_at: '2022-03-11T20:09:02.108+01:00',
            nickname: 'Transporteur P.',
            gender: 'F',
            firstname: 'Transporteur',
            business_name: '',
            phone_verified: true,
            role: 'customer',
            sign_up_finished: true,
            v2_id: null,
            deleted_at: null,
            rate: 0,
            banned_at: null,
            referral_code: 'JULTP1510',
            accepted_cgu_version: 2,
            rating_count: 3,
            email_verified: true,
            response_percent: 100,
            avatar:
              '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2NFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd018116750a8e8b98d7313db2a3d97275616a69/maxresdefault%20(1).jpg?disposition=attachment',
            avatar_key: 'gf20d2kphgkc9zmto4g8u9fbcv9d',
            kyc_validated: true,
            identity_validated: false,
            role_label: 'Particulier',
            current_cgu_version: 2,
          },
          ride_state_histories: [],
          previous_pay_in: false,
          conversations: { count: 0, unreaded_messages: 0 },
          from_address: 'Lille, 59800',
          to_address: 'Valenciennes, 59300',
          from_country: 'France',
          to_country: 'France',
          offers_made_by_others_count: 0,
          volume_only_for_pro: false,
          photos: [
            {
              id: 971,
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0VFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b011d368451d97ef77d8ea3906a2f5765dea35e3/5ce4186d00d978def7900564_1316-WM-COVR-05%202.jpg?disposition=attachment',
              url_key: '4yvjf6pbniakvse7yitnbqaottar',
            },
            {
              id: 972,
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0lFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d97aeab3dac7c30fa63da3c057802e48c972c69/7d843bd79c9b4ccb8455770b8976e059_15_1920.jpg?disposition=attachment',
              url_key: '73us6dotus5aqc92ch62xa18ity6',
            },
          ],
          from: { lat: 50.63194, lon: 3.0575 },
          to: { lat: 50.35917, lon: 3.525 },
          distance: 44.87177497523949,
          bearing: 132.34647600489632,
        },
        sort: [1647336980256],
      },
      {
        _index: 'rides',
        _type: '_doc',
        _id: 3,
        _score: null,
        _source: {
          id: 3,
          title: 'Déménagement: 3.1m3',
          description: null,
          owner_id: 1502,
          from_lat: 48.866536,
          to_lat: 43.401443,
          ga_sent: null,
          price: 20600,
          created_at: '2022-03-14T21:12:31.549+01:00',
          updated_at: '2022-03-14T21:21:23.680+01:00',
          from_lng: 2.355924,
          to_lng: 3.695977,
          from_is_flexible: false,
          from_pickup_date: '2022-04-04T12:00:00.000+02:00',
          to_is_flexible: false,
          to_pickup_date: '2022-04-16T23:59:59.999+02:00',
          is_packaged: null,
          is_passenger: false,
          volume: 3.1,
          environment: 'relocation',
          deleted_at: null,
          slug: 'demenagement-3-1m3',
          rider_extra_information: 'test',
          from_need_help: true,
          from_need_help_floor: 3,
          from_need_help_elevator: false,
          from_need_help_furniture_lift: false,
          to_need_help: true,
          to_need_help_floor: 1,
          to_need_help_elevator: false,
          to_need_help_furniture_lift: false,
          state: 'published',
          moderated_by: null,
          moderated_at: null,
          moderated_reason_content: null,
          owner_status: 'sender',
          completed_at: null,
          published_at: '2022-03-14T21:12:33.404+01:00',
          gat_sent: false,
          last_activity_at: '2022-03-14T21:12:31.553+01:00',
          validated_by_id: null,
          fees: 4300,
          v2_id: null,
          environment_kind: null,
          api_application_id: null,
          seller_tracking: '3247F5C090C79AD9',
          buyer_tracking: '3144AEEA6361C5BB',
          external_id: null,
          content_value: null,
          offers_count: 0,
          last_edited_at: '2022-03-14T21:21:23.680+01:00',
          last_standby_at: null,
          managed_by_id: null,
          is_automatic: false,
          sinister: false,
          removed_at: null,
          price_formula: 'standard',
          has_heavy_objects: false,
          packaging_needed: false,
          suggested_price: 18700,
          published_price: null,
          rider_price: 20600,
          owner: {
            id: 1502,
            last_sign_in_at: '2022-03-14T09:19:55.206+01:00',
            nickname: 'Homer S.',
            gender: 'M',
            firstname: 'Homer',
            business_name: null,
            phone_verified: true,
            role: 'customer',
            sign_up_finished: true,
            v2_id: null,
            deleted_at: null,
            rate: 0,
            banned_at: null,
            referral_code: 'DAIHS101',
            accepted_cgu_version: 2,
            rating_count: 3,
            email_verified: true,
            response_percent: 0,
            avatar:
              '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjBEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc0f4296123a2595bd114ec7a87b598d2186f448/wink.png?disposition=attachment',
            avatar_key: '544tqqnq3venrqylfc6ffup6wvp9',
            kyc_validated: true,
            identity_validated: true,
            role_label: 'Particulier',
            current_cgu_version: 2,
          },
          ride_state_histories: [],
          previous_pay_in: false,
          conversations: { count: 0, unreaded_messages: 0 },
          from_address: 'Paris, 75003',
          to_address: 'Sète, 34200',
          from_country: 'France',
          to_country: 'France',
          offers_made_by_others_count: 0,
          volume_only_for_pro: false,
          photos: [
            {
              id: 974,
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1FFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e66fe8f6c6f3ff56462edf202dd433ffcbce91f2/te%CC%81le%CC%81chargement.jpeg?disposition=attachment',
              url_key: 'o7oislri74d7j8iwwgr533dbd1d6',
            },
            {
              id: 975,
              url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1VFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--270926269fc74f5e380484cc416104c1076c2027/wink.png?disposition=attachment',
              url_key: 'wpo99pfk85uhuw8rrxz5q0go8sjw',
            },
          ],
          from: { lat: 48.866536, lon: 2.355924 },
          to: { lat: 43.401443, lon: 3.695977 },
          distance: 616.3728641748479,
          bearing: 169.86883077259608,
        },
        sort: [1647289283680],
      },
      {
        _index: 'rides',
        _type: '_doc',
        _id: 4,
        _score: null,
        _source: {
          id: 4,
          title: 'Ampli (hifi, guitare), Epandeur à fumier',
          description: null,
          owner_id: 1501,
          from_lat: 48.85658,
          to_lat: 48.85658,
          ga_sent: null,
          price: 66400,
          created_at: '2022-03-03T22:52:01.051+01:00',
          updated_at: '2022-03-14T15:31:51.737+01:00',
          from_lng: 2.35183,
          to_lng: 2.35183,
          from_is_flexible: false,
          from_pickup_date: '2022-03-03T12:00:00.000+01:00',
          to_is_flexible: false,
          to_pickup_date: '2022-03-29T15:31:51.726+02:00',
          is_packaged: null,
          is_passenger: false,
          volume: 20.2,
          environment: 'objects',
          deleted_at: null,
          slug: 'ampli-hifi-guitare-epandeur-a-fumier',
          rider_extra_information: '',
          from_need_help: false,
          from_need_help_floor: null,
          from_need_help_elevator: false,
          from_need_help_furniture_lift: false,
          to_need_help: false,
          to_need_help_floor: null,
          to_need_help_elevator: false,
          to_need_help_furniture_lift: false,
          state: 'published',
          moderated_by: null,
          moderated_at: null,
          moderated_reason_content: null,
          owner_status: 'recipient',
          completed_at: null,
          published_at: '2022-03-04T14:31:09.775+01:00',
          gat_sent: false,
          last_activity_at: '2022-03-14T15:31:51.627+01:00',
          validated_by_id: null,
          fees: 13600,
          v2_id: null,
          environment_kind: null,
          api_application_id: null,
          seller_tracking: '3D1988A43E047156',
          buyer_tracking: 'A06DB30C0AB6DFC9',
          external_id: null,
          content_value: null,
          offers_count: 1,
          last_edited_at: '2022-03-14T15:31:51.737+01:00',
          last_standby_at: null,
          managed_by_id: null,
          is_automatic: false,
          sinister: false,
          removed_at: null,
          price_formula: null,
          has_heavy_objects: false,
          packaging_needed: false,
          suggested_price: 68900,
          published_price: 68900,
          rider_price: 66400,
          owner: {
            id: 1501,
            last_sign_in_at: '2022-03-11T16:11:17.734+01:00',
            nickname: 'Marge S.',
            gender: 'F',
            firstname: 'Marge',
            business_name: 'DAICOCOLIS',
            phone_verified: true,
            role: 'shop_owner',
            sign_up_finished: true,
            v2_id: null,
            deleted_at: null,
            rate: 1.15,
            banned_at: null,
            referral_code: 'DAIMS101',
            accepted_cgu_version: 2,
            rating_count: 13,
            email_verified: true,
            response_percent: 0,
            avatar:
              '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnNEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84079328a5f346c58af9b97e16bb84e22c4f0d86/store.png?disposition=attachment',
            avatar_key: 'am6pbnr14xrccwpm0biasr767vio',
            kyc_validated: false,
            identity_validated: false,
            role_label: 'Commerçant',
            current_cgu_version: 2,
          },
          ride_state_histories: [
            {
              id: 3175,
              state: 'moderated',
              previous_state: 'published',
              created_at: '2022-03-04T14:29:17.033+01:00',
              updated_at: '2022-03-04T14:29:17.033+01:00',
              ride_id: 7017,
              user_id: 1493,
              event: 'moderate!',
            },
            {
              id: 3176,
              state: 'published',
              previous_state: 'moderated',
              created_at: '2022-03-04T14:31:09.751+01:00',
              updated_at: '2022-03-04T14:31:09.751+01:00',
              ride_id: 7017,
              user_id: 1501,
              event: 'publish!',
            },
            {
              id: 3189,
              state: 'in_progress',
              previous_state: 'published',
              created_at: '2022-03-07T09:54:28.406+01:00',
              updated_at: '2022-03-07T09:54:28.406+01:00',
              ride_id: 7017,
              user_id: null,
              event: 'start!',
            },
            {
              id: 3163,
              state: 'published',
              previous_state: 'creating',
              created_at: '2022-03-03T22:52:01.110+01:00',
              updated_at: '2022-03-03T22:52:01.110+01:00',
              ride_id: 7017,
              user_id: 1501,
              event: 'publish!',
            },
          ],
          previous_pay_in: true,
          conversations: { count: 1, unreaded_messages: 0 },
          from_address: 'Paris, 75004',
          to_address: 'Paris, 75004',
          from_country: 'France',
          to_country: 'France',
          offers_made_by_others_count: 1,
          volume_only_for_pro: true,
          photos: [],
          from: { lat: 48.85658, lon: 2.35183 },
          to: { lat: 48.85658, lon: 2.35183 },
          distance: 0,
          bearing: 0,
        },
        sort: [1647268311737],
      },
    ],
  },
}
export const RIDES_DATA_DYNAMIC = () => {
  const ids_5 = new Array(5).fill(0).map(() => uuidv4())
  const coordinates_5 = new Array(5).fill(0).map(() => ({ from: generateLonLatFloat(), to: generateLonLatFloat() }))
  log(coordinates_5)
  const RIDE_HITS_HITS = RIDES_DATA_STATIC.hits.hits.map((ride, index) => {
    const lonlatLevel = overwriteLonLatObj(ride, coordinates_5[index], ids_5[index])
    return merge({}, ride, lonlatLevel)
  })

  return merge({}, RIDES_DATA_STATIC, { hits: { hits: RIDE_HITS_HITS } })

  return {
    took: 2,
    timed_out: false,
    _shards: { total: 1, successful: 1, skipped: 0, failed: 0 },
    hits: {
      total: { value: 28, relation: 'eq' },
      max_score: null,
      hits: [
        {
          _index: 'rides',
          _type: '_doc',
          _id: ids_5[0],
          _score: null,
          _source: {
            id: ids_5[0],
            title: 'Meuble tv',
            description: null,
            owner_id: 1511,
            from_lat: 48.85658,
            to_lat: 45.75889,
            ga_sent: null,
            price: 5400,
            created_at: '2022-03-18T14:28:46.320+01:00',
            updated_at: '2022-03-18T14:28:58.343+01:00',
            from_lng: 2.35183,
            to_lng: 4.84139,
            from_is_flexible: false,
            from_pickup_date: '2022-03-21T12:00:00.000+01:00',
            to_is_flexible: false,
            to_pickup_date: '2022-03-31T23:59:59.999+02:00',
            is_packaged: null,
            is_passenger: false,
            volume: 0.3,
            environment: 'objects',
            deleted_at: null,
            slug: 'meuble-tv-2a14b24e-c862-417e-9e2d-4bad063c75f6',
            rider_extra_information: '',
            from_need_help: false,
            from_need_help_floor: null,
            from_need_help_elevator: null,
            from_need_help_furniture_lift: false,
            to_need_help: false,
            to_need_help_floor: null,
            to_need_help_elevator: null,
            to_need_help_furniture_lift: false,
            state: 'published',
            moderated_by: null,
            moderated_at: null,
            moderated_reason_content: null,
            owner_status: 'sender',
            completed_at: null,
            published_at: '2022-03-18T14:28:46.375+01:00',
            gat_sent: false,
            last_activity_at: '2022-03-18T14:28:46.323+01:00',
            validated_by_id: null,
            fees: 1200,
            v2_id: null,
            environment_kind: null,
            api_application_id: null,
            seller_tracking: 'E2CDD16E1974D8C0',
            buyer_tracking: '132152975D6856A8',
            external_id: null,
            content_value: null,
            offers_count: 0,
            last_edited_at: '2022-03-18T14:28:58.343+01:00',
            last_standby_at: null,
            managed_by_id: null,
            is_automatic: false,
            sinister: false,
            removed_at: null,
            price_formula: null,
            has_heavy_objects: false,
            packaging_needed: false,
            suggested_price: 6600,
            published_price: null,
            rider_price: 5400,
            owner: {
              id: 1511,
              last_sign_in_at: '2022-01-17T15:47:11.873+01:00',
              nickname: 'Emma Z.',
              gender: 'F',
              firstname: 'Emma',
              business_name: '',
              phone_verified: true,
              role: 'customer',
              sign_up_finished: true,
              v2_id: null,
              deleted_at: null,
              rate: null,
              banned_at: null,
              referral_code: 'EMMEZ171',
              accepted_cgu_version: 2,
              rating_count: 0,
              email_verified: true,
              response_percent: 0,
              kyc_validated: false,
              identity_validated: false,
              role_label: 'Particulier',
              current_cgu_version: 2,
            },
            ride_state_histories: [],
            previous_pay_in: false,
            conversations: { count: 0, unreaded_messages: 0 },
            from_address: 'Paris, 75004',
            to_address: 'Lyon, 69003',
            from_country: 'France',
            to_country: 'France',
            offers_made_by_others_count: 0,
            volume_only_for_pro: false,
            photos: [],
            from: { lat: 48.85658, lon: 2.35183 },
            to: { lat: 45.75889, lon: 4.84139 },
            distance: 392.21852717235214,
            bearing: 150.48998216586,
          },
          sort: [1647610138343],
        },
        {
          _index: 'rides',
          _type: '_doc',
          _id: ids_5[1],
          _score: null,
          _source: {
            id: ids_5[1],
            title: 'Test',
            description: null,
            owner_id: 218,
            from_lat: 50.63194,
            to_lat: 36.7,
            ga_sent: null,
            price: 4100,
            created_at: '2022-03-15T18:08:54.970+01:00',
            updated_at: '2022-03-15T18:09:11.471+01:00',
            from_lng: 3.0575,
            to_lng: -6.11667,
            from_is_flexible: false,
            from_pickup_date: '2022-03-17T12:00:00.000+01:00',
            to_is_flexible: false,
            to_pickup_date: '2022-03-24T23:59:59.999+01:00',
            is_packaged: null,
            is_passenger: false,
            volume: 0.6,
            environment: 'objects',
            deleted_at: null,
            slug: 'test-a40d8dd8-b9aa-4dc7-a3aa-ffe3be3b2fd4',
            rider_extra_information: '',
            from_need_help: false,
            from_need_help_floor: null,
            from_need_help_elevator: null,
            from_need_help_furniture_lift: false,
            to_need_help: false,
            to_need_help_floor: null,
            to_need_help_elevator: null,
            to_need_help_furniture_lift: false,
            state: 'published',
            moderated_by: null,
            moderated_at: null,
            moderated_reason_content: null,
            owner_status: 'recipient',
            completed_at: null,
            published_at: '2022-03-15T18:08:55.059+01:00',
            gat_sent: false,
            last_activity_at: '2022-03-15T18:08:54.974+01:00',
            validated_by_id: null,
            fees: 900,
            v2_id: null,
            environment_kind: null,
            api_application_id: null,
            seller_tracking: 'A06B971B2C6E2983',
            buyer_tracking: '8F4D5FB43952894D',
            external_id: null,
            content_value: null,
            offers_count: 0,
            last_edited_at: '2022-03-15T18:09:11.471+01:00',
            last_standby_at: null,
            managed_by_id: null,
            is_automatic: false,
            sinister: false,
            removed_at: null,
            price_formula: null,
            has_heavy_objects: false,
            packaging_needed: false,
            suggested_price: 9900,
            published_price: null,
            rider_price: 4100,
            owner: {
              id: 218,
              last_sign_in_at: '2022-03-11T20:09:02.108+01:00',
              nickname: 'Transporteur P.',
              gender: 'F',
              firstname: 'Transporteur',
              business_name: '',
              phone_verified: true,
              role: 'customer',
              sign_up_finished: true,
              v2_id: null,
              deleted_at: null,
              rate: 0,
              banned_at: null,
              referral_code: 'JULTP1510',
              accepted_cgu_version: 2,
              rating_count: 3,
              email_verified: true,
              response_percent: 100,
              avatar:
                '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2NFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd018116750a8e8b98d7313db2a3d97275616a69/maxresdefault%20(1).jpg?disposition=attachment',
              avatar_key: 'gf20d2kphgkc9zmto4g8u9fbcv9d',
              kyc_validated: true,
              identity_validated: false,
              role_label: 'Particulier',
              current_cgu_version: 2,
            },
            ride_state_histories: [],
            previous_pay_in: false,
            conversations: { count: 0, unreaded_messages: 0 },
            from_address: 'Lille, 59800',
            to_address: 'Jerez de la Frontera, 11405',
            from_country: 'France',
            to_country: 'Spain',
            offers_made_by_others_count: 0,
            volume_only_for_pro: false,
            photos: [],
            from: { lat: 50.63194, lon: 3.0575 },
            to: { lat: 36.7, lon: -6.11667 },
            distance: 1712.844302555822,
            bearing: 208.76730023577312,
          },
          sort: [1647364151471],
        },
        {
          _index: 'rides',
          _type: '_doc',
          _id: ids_5[2],
          _score: null,
          _source: {
            id: ids_5[2],
            title: 'Guitarre',
            description: null,
            owner_id: 218,
            from_lat: 50.63194,
            to_lat: 50.35917,
            ga_sent: null,
            price: 2900,
            created_at: '2022-03-11T10:02:09.005+01:00',
            updated_at: '2022-03-15T10:36:20.276+01:00',
            from_lng: 3.0575,
            to_lng: 3.525,
            from_is_flexible: true,
            from_pickup_date: '2022-03-15T12:00:00.000+01:00',
            to_is_flexible: false,
            to_pickup_date: '2022-06-30T23:59:59.999+02:00',
            is_packaged: null,
            is_passenger: false,
            volume: 0.6,
            environment: 'objects',
            deleted_at: null,
            slug: 'guitarre',
            rider_extra_information: '',
            from_need_help: false,
            from_need_help_floor: null,
            from_need_help_elevator: null,
            from_need_help_furniture_lift: false,
            to_need_help: false,
            to_need_help_floor: null,
            to_need_help_elevator: null,
            to_need_help_furniture_lift: false,
            state: 'published',
            moderated_by: null,
            moderated_at: null,
            moderated_reason_content: null,
            owner_status: 'sender',
            completed_at: null,
            published_at: '2022-03-15T10:36:20.271+01:00',
            gat_sent: false,
            last_activity_at: '2022-03-11T10:02:09.010+01:00',
            validated_by_id: null,
            fees: 600,
            v2_id: null,
            environment_kind: null,
            api_application_id: null,
            seller_tracking: 'C14DD027E015373D',
            buyer_tracking: '87E2E4E145F40A12',
            external_id: null,
            content_value: null,
            offers_count: 0,
            last_edited_at: '2022-03-15T10:36:20.256+01:00',
            last_standby_at: null,
            managed_by_id: null,
            is_automatic: false,
            sinister: false,
            removed_at: null,
            price_formula: null,
            has_heavy_objects: false,
            packaging_needed: false,
            suggested_price: 3500,
            published_price: null,
            rider_price: 2900,
            owner: {
              id: 218,
              last_sign_in_at: '2022-03-11T20:09:02.108+01:00',
              nickname: 'Transporteur P.',
              gender: 'F',
              firstname: 'Transporteur',
              business_name: '',
              phone_verified: true,
              role: 'customer',
              sign_up_finished: true,
              v2_id: null,
              deleted_at: null,
              rate: 0,
              banned_at: null,
              referral_code: 'JULTP1510',
              accepted_cgu_version: 2,
              rating_count: 3,
              email_verified: true,
              response_percent: 100,
              avatar:
                '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2NFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd018116750a8e8b98d7313db2a3d97275616a69/maxresdefault%20(1).jpg?disposition=attachment',
              avatar_key: 'gf20d2kphgkc9zmto4g8u9fbcv9d',
              kyc_validated: true,
              identity_validated: false,
              role_label: 'Particulier',
              current_cgu_version: 2,
            },
            ride_state_histories: [],
            previous_pay_in: false,
            conversations: { count: 0, unreaded_messages: 0 },
            from_address: 'Lille, 59800',
            to_address: 'Valenciennes, 59300',
            from_country: 'France',
            to_country: 'France',
            offers_made_by_others_count: 0,
            volume_only_for_pro: false,
            photos: [
              {
                id: 971,
                url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0VFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b011d368451d97ef77d8ea3906a2f5765dea35e3/5ce4186d00d978def7900564_1316-WM-COVR-05%202.jpg?disposition=attachment',
                url_key: '4yvjf6pbniakvse7yitnbqaottar',
              },
              {
                id: 972,
                url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0lFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d97aeab3dac7c30fa63da3c057802e48c972c69/7d843bd79c9b4ccb8455770b8976e059_15_1920.jpg?disposition=attachment',
                url_key: '73us6dotus5aqc92ch62xa18ity6',
              },
            ],
            from: { lat: 50.63194, lon: 3.0575 },
            to: { lat: 50.35917, lon: 3.525 },
            distance: 44.87177497523949,
            bearing: 132.34647600489632,
          },
          sort: [1647336980256],
        },
        {
          _index: 'rides',
          _type: '_doc',
          _id: ids_5[3],
          _score: null,
          _source: {
            id: ids_5[3],
            title: 'Déménagement: 3.1m3',
            description: null,
            owner_id: 1502,
            from_lat: 48.866536,
            to_lat: 43.401443,
            ga_sent: null,
            price: 20600,
            created_at: '2022-03-14T21:12:31.549+01:00',
            updated_at: '2022-03-14T21:21:23.680+01:00',
            from_lng: 2.355924,
            to_lng: 3.695977,
            from_is_flexible: false,
            from_pickup_date: '2022-04-04T12:00:00.000+02:00',
            to_is_flexible: false,
            to_pickup_date: '2022-04-16T23:59:59.999+02:00',
            is_packaged: null,
            is_passenger: false,
            volume: 3.1,
            environment: 'relocation',
            deleted_at: null,
            slug: 'demenagement-3-1m3',
            rider_extra_information: 'test',
            from_need_help: true,
            from_need_help_floor: 3,
            from_need_help_elevator: false,
            from_need_help_furniture_lift: false,
            to_need_help: true,
            to_need_help_floor: 1,
            to_need_help_elevator: false,
            to_need_help_furniture_lift: false,
            state: 'published',
            moderated_by: null,
            moderated_at: null,
            moderated_reason_content: null,
            owner_status: 'sender',
            completed_at: null,
            published_at: '2022-03-14T21:12:33.404+01:00',
            gat_sent: false,
            last_activity_at: '2022-03-14T21:12:31.553+01:00',
            validated_by_id: null,
            fees: 4300,
            v2_id: null,
            environment_kind: null,
            api_application_id: null,
            seller_tracking: '3247F5C090C79AD9',
            buyer_tracking: '3144AEEA6361C5BB',
            external_id: null,
            content_value: null,
            offers_count: 0,
            last_edited_at: '2022-03-14T21:21:23.680+01:00',
            last_standby_at: null,
            managed_by_id: null,
            is_automatic: false,
            sinister: false,
            removed_at: null,
            price_formula: 'standard',
            has_heavy_objects: false,
            packaging_needed: false,
            suggested_price: 18700,
            published_price: null,
            rider_price: 20600,
            owner: {
              id: 1502,
              last_sign_in_at: '2022-03-14T09:19:55.206+01:00',
              nickname: 'Homer S.',
              gender: 'M',
              firstname: 'Homer',
              business_name: null,
              phone_verified: true,
              role: 'customer',
              sign_up_finished: true,
              v2_id: null,
              deleted_at: null,
              rate: 0,
              banned_at: null,
              referral_code: 'DAIHS101',
              accepted_cgu_version: 2,
              rating_count: 3,
              email_verified: true,
              response_percent: 0,
              avatar:
                '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjBEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc0f4296123a2595bd114ec7a87b598d2186f448/wink.png?disposition=attachment',
              avatar_key: '544tqqnq3venrqylfc6ffup6wvp9',
              kyc_validated: true,
              identity_validated: true,
              role_label: 'Particulier',
              current_cgu_version: 2,
            },
            ride_state_histories: [],
            previous_pay_in: false,
            conversations: { count: 0, unreaded_messages: 0 },
            from_address: 'Paris, 75003',
            to_address: 'Sète, 34200',
            from_country: 'France',
            to_country: 'France',
            offers_made_by_others_count: 0,
            volume_only_for_pro: false,
            photos: [
              {
                id: 974,
                url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1FFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e66fe8f6c6f3ff56462edf202dd433ffcbce91f2/te%CC%81le%CC%81chargement.jpeg?disposition=attachment',
                url_key: 'o7oislri74d7j8iwwgr533dbd1d6',
              },
              {
                id: 975,
                url: '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1VFIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--270926269fc74f5e380484cc416104c1076c2027/wink.png?disposition=attachment',
                url_key: 'wpo99pfk85uhuw8rrxz5q0go8sjw',
              },
            ],
            from: { lat: 48.866536, lon: 2.355924 },
            to: { lat: 43.401443, lon: 3.695977 },
            distance: 616.3728641748479,
            bearing: 169.86883077259608,
          },
          sort: [1647289283680],
        },
        {
          _index: 'rides',
          _type: '_doc',
          _id: ids_5[4],
          _score: null,
          _source: {
            id: ids_5[4],
            title: 'Ampli (hifi, guitare), Epandeur à fumier',
            description: null,
            owner_id: 1501,
            from_lat: 45.85658,
            to_lat: 40.85658,
            ga_sent: null,
            price: 66400,
            created_at: '2022-03-03T22:52:01.051+01:00',
            updated_at: '2022-03-14T15:31:51.737+01:00',
            from_lng: 2.35183,
            to_lng: 2.35183,
            from_is_flexible: false,
            from_pickup_date: '2022-03-03T12:00:00.000+01:00',
            to_is_flexible: false,
            to_pickup_date: '2022-03-29T15:31:51.726+02:00',
            is_packaged: null,
            is_passenger: false,
            volume: 20.2,
            environment: 'objects',
            deleted_at: null,
            slug: 'ampli-hifi-guitare-epandeur-a-fumier',
            rider_extra_information: '',
            from_need_help: false,
            from_need_help_floor: null,
            from_need_help_elevator: false,
            from_need_help_furniture_lift: false,
            to_need_help: false,
            to_need_help_floor: null,
            to_need_help_elevator: false,
            to_need_help_furniture_lift: false,
            state: 'published',
            moderated_by: null,
            moderated_at: null,
            moderated_reason_content: null,
            owner_status: 'recipient',
            completed_at: null,
            published_at: '2022-03-04T14:31:09.775+01:00',
            gat_sent: false,
            last_activity_at: '2022-03-14T15:31:51.627+01:00',
            validated_by_id: null,
            fees: 13600,
            v2_id: null,
            environment_kind: null,
            api_application_id: null,
            seller_tracking: '3D1988A43E047156',
            buyer_tracking: 'A06DB30C0AB6DFC9',
            external_id: null,
            content_value: null,
            offers_count: 1,
            last_edited_at: '2022-03-14T15:31:51.737+01:00',
            last_standby_at: null,
            managed_by_id: null,
            is_automatic: false,
            sinister: false,
            removed_at: null,
            price_formula: null,
            has_heavy_objects: false,
            packaging_needed: false,
            suggested_price: 68900,
            published_price: 68900,
            rider_price: 66400,
            owner: {
              id: 1501,
              last_sign_in_at: '2022-03-11T16:11:17.734+01:00',
              nickname: 'Marge S.',
              gender: 'F',
              firstname: 'Marge',
              business_name: 'DAICOCOLIS',
              phone_verified: true,
              role: 'shop_owner',
              sign_up_finished: true,
              v2_id: null,
              deleted_at: null,
              rate: 1.15,
              banned_at: null,
              referral_code: 'DAIMS101',
              accepted_cgu_version: 2,
              rating_count: 13,
              email_verified: true,
              response_percent: 0,
              avatar:
                '/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdnNEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--84079328a5f346c58af9b97e16bb84e22c4f0d86/store.png?disposition=attachment',
              avatar_key: 'am6pbnr14xrccwpm0biasr767vio',
              kyc_validated: false,
              identity_validated: false,
              role_label: 'Commerçant',
              current_cgu_version: 2,
            },
            ride_state_histories: [
              {
                id: 3175,
                state: 'moderated',
                previous_state: 'published',
                created_at: '2022-03-04T14:29:17.033+01:00',
                updated_at: '2022-03-04T14:29:17.033+01:00',
                ride_id: 7017,
                user_id: 1493,
                event: 'moderate!',
              },
              {
                id: 3176,
                state: 'published',
                previous_state: 'moderated',
                created_at: '2022-03-04T14:31:09.751+01:00',
                updated_at: '2022-03-04T14:31:09.751+01:00',
                ride_id: 7017,
                user_id: 1501,
                event: 'publish!',
              },
              {
                id: 3189,
                state: 'in_progress',
                previous_state: 'published',
                created_at: '2022-03-07T09:54:28.406+01:00',
                updated_at: '2022-03-07T09:54:28.406+01:00',
                ride_id: 7017,
                user_id: null,
                event: 'start!',
              },
              {
                id: 3163,
                state: 'published',
                previous_state: 'creating',
                created_at: '2022-03-03T22:52:01.110+01:00',
                updated_at: '2022-03-03T22:52:01.110+01:00',
                ride_id: 7017,
                user_id: 1501,
                event: 'publish!',
              },
            ],
            previous_pay_in: true,
            conversations: { count: 1, unreaded_messages: 0 },
            from_address: 'Paris, 75004',
            to_address: 'Paris, 75004',
            from_country: 'France',
            to_country: 'France',
            offers_made_by_others_count: 1,
            volume_only_for_pro: true,
            photos: [],
            from: { lat: 48.85658, lon: 2.35183 },
            to: { lat: 48.85658, lon: 2.35183 },
            distance: 0,
            bearing: 0,
          },
          sort: [1647268311737],
        },
      ],
    },
  }
}
